name: Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate profile metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: eeminionn
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Santiago

          # Plugins
          plugins: languages, achievements
          plugins_languages: yes
          plugins_languages_sections: most-used
          plugins_languages_details: percentage, bytes-size
          plugins_languages_limit: 8
          plugins_achievements: yes
          plugins_achievements_display: compact
          plugins_achievements_threshold: C

          # Output
          output_action: commit
          committer_branch: main
          committer_message: "chore(metrics): update profile dashboard"
