name: Metrics (showcase, clean)

on:
  # Se actualiza 4 veces al día y en cada push a main
  schedule:
    - cron: "0 0,6,12,18 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate profile metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # --- Base / Perfil ---
          user: eeminionn
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Santiago

          # --- Lenguajes ---
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # --- Calendario isométrico de commits ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # --- Hábitos de trabajo (últimas 2 semanas) ---
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes

          # --- Repositorios destacados / fijados ---
          plugin_repositories: yes
          plugin_repositories_featured: eeminionn/eeminionn
          plugin_repositories_pinned: 3

          # --- Stargazers (charts sin worldmap) ---
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_worldmap: false

          # --- Líneas de código ---
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_lines_repositories_limit: 8
          plugin_lines_history_limit: 365
          plugin_lines_delay: 0

          # --- Salida ---
          filename: metrics.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore(metrics): update profile dashboard"

          # No fallar por warnings menores
          plugins_errors_fatal: false
